config: Add role for setup laravel framework
tenantcloud/ansible-role-laravel pull request #1
Opened 2020-03-10 14:16 UTC by vikfedkiv

2020-03-11 08:19 UTC, BrunIF requested changes

2020-03-11 08:19 UTC, BrunIF commented on README.md
> +ansible_role_tenantcloud.laravel
Підтягни зміни з девелопмента

2020-03-11 08:19 UTC, BrunIF commented on README.md
> +work_dir: myprojectdirectory
Тут повинен бути відносний чи абсолютний шлях? Я б робив абсолютний. Якщо відносний, то від користувача хоча б.

2020-03-11 08:19 UTC, BrunIF commented on README.md
> +mysql_database: mydatabase
Може краще додати root користувача, щоб він зробив для проекту свого користувача і свою базу. Розмежування прав досутпу.

2020-03-11 08:19 UTC, BrunIF commented on README.md
> +minio_bucket: myminiobucket
а для прода чи для тестових треба minio?
Якщо потрібні s3 ключі, то так їх і називати. minio - то локальна заміна s3.

2020-03-11 08:19 UTC, BrunIF commented on README.md
> +* For Emailer:
Це не для емейлера. Це для проекту Laravel. По тексту замінити emailer -> laravel

2020-03-11 08:19 UTC, BrunIF commented on README.md
> +    minio_bucket: emailer
переробити до попередніх зауважень.

2020-03-11 08:19 UTC, BrunIF commented on meta/main.yml
> +        - stretch
Стяни зміни. Я там і MacOS додав. Його буде @odebretseni  робити

2020-03-11 08:19 UTC, BrunIF commented on tasks/download-project.yml
> +    dest: /var/www/html/{{ work_dir }}
те що я писав вище. Треба абсолютний шлях у змінну.

2020-03-11 08:19 UTC, BrunIF commented on tasks/download-project.yml
> +  when: ansible_distribution == 'Ubuntu'
Тут не робиться ця перевірка. 
Дану перевірку потрібно робити у main.yml.

2020-03-11 08:19 UTC, BrunIF commented on tasks/main.yml
> +- include: setup-project.yml
Додати перевірку і для ubuntu свій сценарій, для macos свій

2020-03-11 08:19 UTC, BrunIF commented on tasks/setup-environment.yml
> +    line: 'DB_USERNAME={{ mysql_user }}'
це не можна зробити циклом? 
і шляхи...

2020-03-11 08:19 UTC, BrunIF commented on tasks/setup-project.yml
> +  with_items:
це ж деприкейтед. loop

2020-03-11 08:19 UTC, BrunIF commented on tasks/setup-project.yml
> +- name: Update apt cache if repo was added.
в попередньому таску не можна оновити?

2020-03-11 08:19 UTC, BrunIF commented on templates/emailer.dev.conf
> +server {
розширення файлу `j2`

2020-03-11 08:19 UTC, BrunIF commented on templates/emailer.dev.conf
> +    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
залишити тільки 
`ssl_protocols TLSv1.2;`

2020-03-11 08:19 UTC, BrunIF commented on templates/emailer.dev.conf
> +    ssl_ciphers "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:EC
замінити 
`    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
`

2020-03-11 08:19 UTC, BrunIF commented on templates/emailer.dev.conf
> +    }
коли це вже видалите?

2020-03-11 08:22 UTC, vikfedkiv commented on README.md
> +work_dir: myprojectdirectory
То просто назва папки з проектом. На Ubuntu у нас всі нові лінки використовують /var/www/html/

2020-03-11 10:11 UTC, vikfedkiv commented on tasks/setup-project.yml
> +- name: Update apt cache if repo was added.
Update cache робиться тільки коли добавлений репозиторій Nodejs. Інакше він пропускається.

2020-03-16 12:40 UTC, BrunIF requested changes

2020-03-16 12:40 UTC, BrunIF commented on meta/main.yml
>    company: "TenantCloud LLC"
Copy - paste

2020-03-16 12:40 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
> +    regexp: "^bitbucket\\.org"
Без цього хіба воно не буде клонувати? 
Перевір

2020-03-16 12:40 UTC, BrunIF commented on templates/nginx.conf.j2
> +
секцію з сокетами через IF

2020-03-16 12:40 UTC, BrunIF commented on tests/test.yml
> +    - laravel
tenantcloud.laravel

2020-03-19 10:39 UTC, BrunIF approved these changes

2020-03-19 10:39 UTC, merged