Add role for setup laravel framework for macosx
tenantcloud/ansible-role-laravel pull request #2
Opened 2020-03-16 15:05 UTC by odebretseni

2020-03-17 07:02 UTC, BrunIF requested changes

2020-03-17 07:02 UTC, BrunIF commented on README.md
> +tenantcloud.laravel
Чого вам не подобається нормальна, а не машинна назва?

2020-03-17 07:02 UTC, BrunIF commented on README.md
> +  - tc-dg
Це взагалі зайве. Це публічний репозиторій. Тут таке не варто і не можна писати!

2020-03-17 07:02 UTC, BrunIF commented on meta/main.yml
>    platforms:
Linux для чого видаляти?

2020-03-17 07:02 UTC, BrunIF commented on tasks/macosx-setup-project.yml
> +    regexp: "^bitbucket\\.org"
перевірити необхідність

2020-03-17 07:02 UTC, BrunIF commented on tasks/macosx-setup-project.yml
> +  changed_when: false
Для чого ? 
У нас має бути налаштований npm. Чи будеш кожного разу перевстановлювати?

2020-03-17 07:02 UTC, BrunIF commented on tasks/macosx-setup-project.yml
> +    state: link
треба це зафіксити по іншому. Якщо нода є. Версія та, що треба а ти будеш шукати nvm? Це не завжання цієї ролі.

2020-03-17 07:02 UTC, BrunIF commented on tasks/macosx-setup-project.yml
> +    PATH: "{{ lookup('env','PATH') }}"
Зробити через змінні або yarn або npm

2020-03-17 07:02 UTC, BrunIF commented on tasks/main.yml
> +  when: ansible_distribution == "MacOSX"
Вітя почав перший, то ж підтягуй його зміни

2020-03-17 07:02 UTC, BrunIF commented on vars/main.yml
> +ansible_python_interpreter: "/usr/local/bin/python3"
Цього не потрібно. Є ж інвенторі файл.

2020-03-17 07:02 UTC, BrunIF commented on vars/main.yml
> +nvm_node_version: "v10.19.0"
подати з цим. Софт має бути встановлений.

2020-03-17 11:04 UTC, odebretseni commented on tasks/macosx-setup-project.yml
> +    state: link
це треба буде зафіксити глобальніше - я поки не знаю як

2020-03-17 11:04 UTC, odebretseni commented on tasks/macosx-setup-project.yml
> +    regexp: "^bitbucket\\.org"
будуть підготовлені ключі

2020-03-17 11:05 UTC, odebretseni commented on tasks/macosx-setup-project.yml
> +    PATH: "{{ lookup('env','PATH') }}"
тут трішки не зрозумів

2020-03-17 11:05 UTC, odebretseni commented on tasks/main.yml
> +  when: ansible_distribution == "MacOSX"
буду обєднювати з його репозиторієм додам

2020-03-17 12:24 UTC, odebretseni commented on tasks/macosx-setup-project.yml
> +    PATH: "{{ lookup('env','PATH') }}"
зрозумів

2020-03-19 06:42 UTC, BrunIF requested changes

2020-03-19 06:42 UTC, BrunIF commented on meta/main.yml
> +  min_ansible_version: BSD
fix

2020-03-19 06:42 UTC, BrunIF commented on tasks/macosx-setup-project.yml
> +    - {path: '/Users/{{ work_user }}/{{ work_dir }}/{{ work_domain }}/.env', regexp: '^APP_URL=', line: 'APP_URL=https://{{ work_domain }}'}
`/Users/{{ work_user }}/{{ work_dir }}/{{ work_domain }}` - дуже довго.

2020-03-19 06:42 UTC, BrunIF commented on templates/vhost.conf.j2
> +server {
Опційно зробити, щоб були сокети.

2020-03-20 10:52 UTC, closed without merging