Refactoring 2.1
tenantcloud/ansible-role-laravel pull request #5
Opened 2020-03-23 20:34 UTC by odebretseni

2020-03-24 07:52 UTC, BrunIF approved these changes

2020-03-24 07:52 UTC, BrunIF commented on tasks/macosx-setup-mailcatcher.yml
> +  changed_when: false
https://docs.ansible.com/ansible/latest/modules/gem_module.html

У мене встановило у `~/.gem/ruby/2.6.0/bin/mailcatcher`
навіть без root встановлюється

2020-03-24 07:52 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
> +    - {path: '{{ work_dir }}/.env', regexp: '^S3_USE_ENDPOINT=', line: 'S3_USE_ENDPOINT=true'}
з пробілами воно читалося краще. А чого прибрав?

2020-03-24 07:52 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
>      path: "{{ work_dir }}"
Переносимо це у `sh/install.sh`

2020-03-24 07:52 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
>      arguments: hirak/prestissimo
мабуть також у `sh/install.sh`

2020-03-24 07:52 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
> +    path: "{{ ansible_env.HOME }}/.log1"
`.log1` ?

2020-03-24 07:52 UTC, BrunIF commented on templates/horizon-macosx.conf.j2
> +stdout_logfile=/usr/local/var/log/supervisor-horizon-{{ work_domain }}.log
переновимо у install.sh

2020-03-24 07:52 UTC, BrunIF commented on templates/mailcatcher-macosx.conf.j2
> +stdout_logfile=/usr/local/var/log/supervisor-mailcatcher-{{ work_domain }}.log
конфіг підходить і для Linux. 
Але якщо кілька проектів піднімеш, то скільки ж у тебе буде mailcatcher`ів?

2020-03-24 07:52 UTC, BrunIF commented on templates/supervisord-macosx.conf.j2
> +files = /usr/local/etc/supervisor.d/*.ini
це не має бути у ролі з підняттям проекту. Це робиться при встановленні софта, а не проекту.

2020-03-24 08:06 UTC, odebretseni commented on tasks/ubuntu-setup-project.yml
> +    - {path: '{{ work_dir }}/.env', regexp: '^S3_USE_ENDPOINT=', line: 'S3_USE_ENDPOINT=true'}
https://monosnap.com/file/ZR4zE8BGRdMPYnA8aQPd2weHKdE3Kc

2020-03-24 08:09 UTC, odebretseni commented on tasks/ubuntu-setup-project.yml
>      path: "{{ work_dir }}"
ок

2020-03-24 08:10 UTC, odebretseni commented on tasks/ubuntu-setup-project.yml
>      arguments: hirak/prestissimo
ok

2020-03-24 08:11 UTC, odebretseni commented on tasks/ubuntu-setup-project.yml
> +    path: "{{ ansible_env.HOME }}/.log1"
так це Віті зміни - https://monosnap.com/file/ixg0LxrUIcXJ3E6JTWzF4EAkiDe8Ek

2020-03-24 08:11 UTC, odebretseni commented on templates/horizon-macosx.conf.j2
> +stdout_logfile=/usr/local/var/log/supervisor-horizon-{{ work_domain }}.log
ок

2020-03-24 08:12 UTC, odebretseni commented on templates/mailcatcher-macosx.conf.j2
> +stdout_logfile=/usr/local/var/log/supervisor-mailcatcher-{{ work_domain }}.log
згідний, він ж все відловлює - навіщо я його під кожен проект переіменовую...

2020-03-24 08:14 UTC, odebretseni commented on templates/supervisord-macosx.conf.j2
> +files = /usr/local/etc/supervisor.d/*.ini
ми забираємо повністю згадки про інстал supervisor з цієї ролі?

2020-03-24 13:02 UTC, BrunIF requested changes

2020-03-24 13:02 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
>      path: "{{ work_dir }}"
так видаляй таск

2020-03-24 13:02 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
>      arguments: hirak/prestissimo
видаляй

2020-03-24 13:02 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
> +    path: "{{ ansible_env.HOME }}/.log1"
я там йому також написав.

2020-03-24 13:02 UTC, BrunIF commented on tasks/ubuntu-setup-project.yml
> +#   register: schedule_added
можна видаляти

2020-03-24 13:02 UTC, BrunIF commented on defaults/main.yml
> +schedule: "false"
видаляємо. Це буде у `sh/install.sh`

2020-03-25 14:01 UTC, BrunIF requested changes

2020-03-25 14:01 UTC, BrunIF commented on README.md
> +    project_git: 'git@bitbucket.org:mycompany/laravel.git'
https://github.com/tenantcloud/laravel-demo-project

2020-03-26 08:47 UTC, BrunIF commented on .travis.yml
> +      - python-pip
то тобі треба все ж `python-pip` чи `python-pip3`
у варсах ти пишеш таке:
```yaml
ansible_python_interpreter: "/usr/local/bin/python3"
```

2020-03-26 13:00 UTC, odebretseni commented on .travis.yml
> +      - python-pip
це не моя частина, в мене для макоса вказано правильно:
https://monosnap.com/file/c43qdQt0mhpRceebi3tHBUqgEaRt6z

2020-03-26 13:45 UTC, BrunIF approved these changes

2020-03-26 13:45 UTC, merged